server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/portfolio
spring.datasource.username=portfolio
spring.datasource.password=monpassword
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

app.upload.dir=/opt/monApp/uploads
